name: push-workflow1
on: push

jobs: 
  push-job:
    runs-on: ubuntu-latest
    steps: 
    - name: step1_
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action
        echo directory move