name: artifact
on: push

jobs:
  upload-artifact:
    runs-on: windows-latest
    steps:
    - name: echo
      run: echo hello-world >hello.txt
    - name: upload artifact
      uses: actions/upload-artifact@v3
        with:
          name: artifact test
          path: ./hello.txt