name: branch-filter
on: 
  push:
    branches: ["dev"]
jobs:
  branch-filter:
    runs-on: windows-latest
    steps:
    - name: echo
      run: echo hello
    - name: runner check
      run: echo '${{toJSON(runner)}}'