name: timeout
on: push

# jobs:
#   timeout:
#     runs-on: ubuntu-latest
#     timeout-minutes: 2
#     steps:
#     - name: loop
#       run: |
#         count=0
#         while true; do
#           echo "seconds: $count"
#           count=$((count+1))
#           sleep 1
#         done
#     - name: echo
#       run: echo hello


jobs:
  timeout:
    runs-on: windows-latest
    timeout-minutes: 2
    steps:
    - name: loop
      run: |
        $count = 0
        while ($true) {
          Write-Host "seconds: $count"
          $count++
          Start-Sleep -Seconds 1
        }
      timeout-minutes: 1
    - name: echo
      run: echo hello